### ISSUE TITLE
Support multiple IPs / Ports

### ISSUE THREAD

**Issue by gmemstr** [jaredallard/minecraft-preempt#1]
Minecraft servers can run on any port, and be dedicated to an interface's IP (e.g a Minecraft host that does shared hosting will assign multiple blocks of IPs to a dedicated box), so this proxy should probably support it (somehow). Preferably from a YAML file as this is how other Minecraft server things handle configuration (plugins, modded servers, etc).

Right now it only listens on `0.0.0.0:25565`, I'm willing to look into this in my off time since it's probably not high priority ;)

**Comment by jaredallard** [comment]
Sure, I can add a block to the yaml configuration that already exists. Is the ask here to support multiple servers? Or just different IP/port combination?

**Comment by gmemstr** [comment]
Preferably, both, so it can scale up past a single server but not require multiple instances of the binary running.
